DATA_INGESTION:
  dataset_source: "kagglehub"
  dataset_name: "aslanahmedov/number-plate-detection"
  download_timeout: 300

DATA_PREPROCESSING:
  annotation_format: "xml"
  target_format: "yolo"
  image_extensions: ['.jpg', '.jpeg', '.png']
  min_image_size: [100, 100]
  max_image_size: [2000, 2000]

YOLOV5_SETUP:
  python_version_requirement: ">=3.8"
  torch_version: ">=1.7"
  force_reinstall: false
  verify_installation: true

# New Training Parameters
MODEL_TRAINING:
  optimizer: "SGD"
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  
  # Early Stopping Parameters
  early_stopping:
    patience: 10          # Stop after N epochs without improvement
    min_delta: 0.001      # Minimum change to qualify as improvement
    monitor_metric: "mAP" # Metric to monitor (mAP, precision, recall)
    mode: "max"           # "max" for mAP, "min" for loss


MODEL_TESTING:
  save_txt: true
  save_conf: true
  save_crop: false
  nosave: false
  agnostic_nms: false
  max_det: 1000

VALIDATION:
  random_seed: 42
  shuffle: true
