DATA_INGESTION:
  dataset_source: "kagglehub"
  dataset_name: "aslanahmedov/number-plate-detection"
  download_timeout: 300

DATA_PREPROCESSING:
  annotation_format: "xml"
  target_format: "yolo"
  image_extensions: ['.jpg', '.jpeg', '.png']
  min_image_size: [100, 100]
  max_image_size: [2000, 2000]

YOLOV5_SETUP:
  python_version_requirement: ">=3.8"
  torch_version: ">=1.7"
  force_reinstall: false
  verify_installation: true

MODEL_TRAINING:
  optimizer: "SGD"
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  early_stopping:
    patience: 10
    min_delta: 0.001
    monitor_metric: "mAP"
    mode: "max"

MODEL_TESTING:
  save_txt: true
  save_conf: true
  save_crop: false
  nosave: false
  agnostic_nms: false
  max_det: 1000

# New OCR Parameters
OCR_INTEGRATION:
  preprocessing:
    resize_factor: 2.0
    gaussian_blur_kernel: [3, 3]
    contrast_alpha: 1.2
    brightness_beta: 10
  
  text_filtering:
    min_text_length: 2
    max_text_length: 15
    allowed_chars: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    remove_special_chars: true
  
  postprocessing:
    format_output: true
    save_cropped_plates: true
    generate_report: true

VALIDATION:
  random_seed: 42
  shuffle: true
